server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/corner}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      auto-commit: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-numbers-for-enums: true
      fail-on-invalid-subtype: true
      fail-on-null-for-primitives: true
      fail-on-trailing-tokens: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  main:
    banner-mode: off

logging:
  level:
    root: warn
jwt:
  signerKey: "55JYJ2DCorJgoTvGpvS8ShO7b69xv2HUaT/fDr0aioKecfJ6C5dAazZjNJiZ07yU"
