server:
  port: 8080
  servlet:
    context-path: /identity

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/identity
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      driverClassName: com.mysql.cj.jdbc.Driver